// Package enigma implements a binary three-rotor Enigma simulator.
package enigma

import (
	"fmt"
	"strings"
)

const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

type rotor struct {
	wiring   [26]int
	reverse  [26]int
	notch    int
	position int
}

// Enigma is a stateful machine for binary data. Encrypting bytes with a new
// instance configured identically decrypts them.
type Enigma struct {
	left      rotor
	middle    rotor
	right     rotor
	reflector [26]int
	plugboard [26]int
}

// New constructs an Enigma I with rotors I-II-III and reflector B.
// positions must contain exactly three Latin letters, from left to right.
// plugboard is a space-separated list of distinct letter pairs, for example
// "AV BS CG". It may be empty.
func New(positions, plugboard string) (*Enigma, error) {
	if len(positions) != 3 {
		return nil, fmt.Errorf("positions должен содержать три буквы A-Z")
	}

	left, err := newRotor("EKMFLGDQVZNTOWYHXUSPAIBRCJ", 'Q', positions[0])
	if err != nil {
		return nil, err
	}
	middle, err := newRotor("AJDKSIRUXBLHWTMCQGZNPYFVOE", 'E', positions[1])
	if err != nil {
		return nil, err
	}
	right, err := newRotor("BDFHJLCPRTXVZNYEIWGAKMUSQO", 'V', positions[2])
	if err != nil {
		return nil, err
	}

	machine := &Enigma{
		left:      left,
		middle:    middle,
		right:     right,
		reflector: wiring("YRUHQSLDPXNGOKMIEBFZCWVJAT"),
	}
	for index := range machine.plugboard {
		machine.plugboard[index] = index
	}
	if err := machine.configurePlugboard(plugboard); err != nil {
		return nil, err
	}
	return machine, nil
}

// TransformByte encrypts one byte, moving the rotors once per input bit.
// Each bit is XORed with a bit generated by the rotor path. XOR makes the
// operation reversible with a fresh machine having the same configuration.
func (machine *Enigma) TransformByte(value byte) byte {
	for bit := 7; bit >= 0; bit-- {
		if machine.nextKeyBit() == 1 {
			value ^= 1 << bit
		}
	}
	return value
}

func (machine *Enigma) nextKeyBit() byte {
	machine.stepRotors()
	encoded := machine.plugboard[0]
	encoded = machine.right.forward(encoded)
	encoded = machine.middle.forward(encoded)
	encoded = machine.left.forward(encoded)
	encoded = machine.reflector[encoded]
	encoded = machine.left.backward(encoded)
	encoded = machine.middle.backward(encoded)
	encoded = machine.right.backward(encoded)
	encoded = machine.plugboard[encoded]

	return byte(encoded & 1)
}

func (machine *Enigma) stepRotors() {
	// This models Enigma's double-step behaviour.
	middleAtNotch := machine.middle.position == machine.middle.notch
	rightAtNotch := machine.right.position == machine.right.notch
	if middleAtNotch {
		machine.left.step()
	}
	if middleAtNotch || rightAtNotch {
		machine.middle.step()
	}
	machine.right.step()
}

func (machine *Enigma) configurePlugboard(value string) error {
	used := [26]bool{}
	for _, pair := range strings.Fields(value) {
		if len(pair) != 2 {
			return fmt.Errorf("некорректная пара plugboard %q", pair)
		}
		first, okFirst := alphabetIndex(pair[0])
		second, okSecond := alphabetIndex(pair[1])
		if !okFirst || !okSecond || first == second || used[first] || used[second] {
			return fmt.Errorf("некорректная пара plugboard %q", pair)
		}
		used[first], used[second] = true, true
		machine.plugboard[first], machine.plugboard[second] = second, first
	}
	return nil
}

func newRotor(wiringText string, notch, position byte) (rotor, error) {
	positionIndex, ok := alphabetIndex(position)
	if !ok {
		return rotor{}, fmt.Errorf("position должен содержать только буквы A-Z")
	}
	return rotor{
		wiring:   wiring(wiringText),
		reverse:  reverseWiring(wiringText),
		notch:    int(notch - 'A'),
		position: positionIndex,
	}, nil
}

func (rotorValue *rotor) step() {
	rotorValue.position = (rotorValue.position + 1) % 26
}

func (rotorValue rotor) forward(value int) int {
	shifted := (value + rotorValue.position) % 26
	return (rotorValue.wiring[shifted] - rotorValue.position + 26) % 26
}

func (rotorValue rotor) backward(value int) int {
	shifted := (value + rotorValue.position) % 26
	return (rotorValue.reverse[shifted] - rotorValue.position + 26) % 26
}

func wiring(value string) [26]int {
	result := [26]int{}
	for index := range result {
		result[index] = int(value[index] - 'A')
	}
	return result
}

func reverseWiring(value string) [26]int {
	result := [26]int{}
	for index, target := range []byte(value) {
		result[target-'A'] = index
	}
	return result
}

func alphabetIndex(value byte) (int, bool) {
	if value >= 'a' && value <= 'z' {
		value -= 'a' - 'A'
	}
	return int(value - 'A'), value >= 'A' && value <= 'Z'
}
